[history_updated.py]
  [test_history_document_open]
    bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1968705
    expected: FAIL
